version: "3.8"
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  mariadb:
    image: mariadb:latest
    env_file: ./database.env
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
  app:
    build:
      context: ../
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ../app:/app
    ports:
      - 4567:4567
    env_file:
      - ./app.env
    command: ruby main.rb
    depends_on:
      - redis
      - mariadb
  lb:
    build:
      context: ../
      dockerfile: ./docker/lb/Dockerfile
    ports:
      - 80:80
    depends_on:
      - app
      - static_server
  static_server:
    build:
      context: ../
      dockerfile: ./docker/static_server/Dockerfile
    ports:
      - 8080:80
    volumes:
      - ../frontend/dist:/assets
  frontend:
    build:
      context: ../
      dockerfile: ./docker/frontend/Dockerfile
    volumes:
      - ../frontend/:/app/
    command: ["bash", "-c", "npx webpack-dev-server"]
