version: "3.8"
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  mariadb:
    image: mariadb:latest
    env_file: ./database.env
    ports:
      - 3306:3306
  app:
    build:
      context: ../
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ../app:/app
    ports:
      - 4567:4567
    env_file:
      - ./app.env
    command: ruby main.rb
    depends_on:
      - lb
      - redis
      - mariadb
  lb:
    build:
      context: ../
      dockerfile: ./docker/lb/Dockerfile
    ports:
      - 80:80
  static_server:
    build:
      context: ../
      dockerfile: ./docker/static_server/Dockerfile
    ports:
      - 80:80
